language: rust
sudo: false

rust:
- 1.36.0
- stable
- beta
- nightly

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- travis-cargo build
- travis-cargo test
- travis-cargo doc -- --no-deps

after_success:
- travis-cargo --only nightly doc-upload

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

notifications:
  email: false
